[
	{
		"doubleclickEnabled":"true",
		"doubleClickStaticAdAppId":"android_test_app",
		"doubleclickUseExternalBrowser":false,
		"doubleClickStaticAdIsCoppaCompliant":false,
		"doubleClickAdIndicatorVisible":false,
		"doubleClickUseBumper":true
	}
]
