[
    {
        "doubleclickEnabled":"true",
        "doubleClickStaticAdAppId":"android_test_app",
        "doubleclickKeyValues":"test=testkeyvalue",
        "doubleclickUseExternalBrowser":"true",
        "doubleClickStaticAdIsCoppaCompliant":true
    }
]