[
    {
        "doubleclickEnabled":"true",
        "doubleclickDartSite":"android_test_app",
        "doubleclickKeyValues":"key=klim_test",
        "doubleclickUseExternalBrowser":"true",
        "doubleClickStaticAdIsCoppaCompliant":"true"
    }
];